version: '3'
services:
  # api:
  #   build: .
  #   container_name: 'api'
  #   restart: unless-stopped
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./.env:/app/.env
  #   depends_on:
  #     - mongo
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    command: --wiredTigerCacheSizeGB 1.5
